### ISSUE TITLE
import db from all 

### ISSUE THREAD

**Issue by BookmDan** [arpanneupane19/Python-Flask-Authentication-Tutorial#3]
I'm having trouble with this part. I keep getting an Traceback error message

**Comment by BookmDan** [comment]
![Screen Shot 2022-10-30 at 3 55 10 PM (2)](https://user-images.githubusercontent.com/8926023/198906003-856c971f-3f5e-493e-8101-fc11347c3411.png)

**Comment by alwinjames7777** [comment]
same issue bro.did you find the solution?

**Comment by BookmDan** [comment]
no not yet

**Comment by peer-pri** [comment]
Did sb found the solution=?

**Comment by alwinjames7777** [comment]
Yes, I did.

**Comment by peer-pri** [comment]
same me too

**Comment by BookmDan** [comment]
What was the issue?

**Comment by peer-pri** [comment]
​
11
app = Flask(__name__)
12
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///database.db'
13
app.config['SECRET_KEY'] = 'thisisasecretkey'
14
db = SQLAlchemy(app)
15
bcrypt = Bcrypt(app)

it need to be like that
